// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAou8oiy9vW-IvI2qZSN60cc0AIRidg65Y',
    appId: '1:487600650426:web:25ab22d864b50ff45a6a83',
    messagingSenderId: '487600650426',
    projectId: 'soulsync-e6539',
    authDomain: 'soulsync-e6539.firebaseapp.com',
    databaseURL: 'https://soulsync-e6539-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soulsync-e6539.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXqeaZC6GW27hmctz_HBXDxU1uHUipV4',
    appId: '1:487600650426:android:4f440d8a037e9f1d5a6a83',
    messagingSenderId: '487600650426',
    projectId: 'soulsync-e6539',
    databaseURL: 'https://soulsync-e6539-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soulsync-e6539.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCbSEsqYxLhwzoPiHtkVNA0S_p4kYa5DE',
    appId: '1:487600650426:ios:570b0184cb97fbad5a6a83',
    messagingSenderId: '487600650426',
    projectId: 'soulsync-e6539',
    databaseURL: 'https://soulsync-e6539-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soulsync-e6539.firebasestorage.app',
    iosBundleId: 'com.example.soulSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCbSEsqYxLhwzoPiHtkVNA0S_p4kYa5DE',
    appId: '1:487600650426:ios:570b0184cb97fbad5a6a83',
    messagingSenderId: '487600650426',
    projectId: 'soulsync-e6539',
    databaseURL: 'https://soulsync-e6539-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soulsync-e6539.firebasestorage.app',
    iosBundleId: 'com.example.soulSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAou8oiy9vW-IvI2qZSN60cc0AIRidg65Y',
    appId: '1:487600650426:web:d128eb64aac91fdb5a6a83',
    messagingSenderId: '487600650426',
    projectId: 'soulsync-e6539',
    authDomain: 'soulsync-e6539.firebaseapp.com',
    databaseURL: 'https://soulsync-e6539-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soulsync-e6539.firebasestorage.app',
  );
}
